[package]
name = "test_splitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asr = { git = "https://github.com/CryZe/asr" }
spinning_top = "0.2.4"

[lib]
crate-type = ["cdylib"]